apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: "512Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: "redis:7.0"
          command: ["redis-server", "--appendonly", "yes"]
          volumeMounts:
            - mountPath: /data
              name: redis-data
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sstester
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: victor
            command: ["python", "-m", "sstester.tester"]
            image: "grimpen/one:%VERSION%"
            imagePullPolicy: IfNotPresent
            env:
            - name: REDIS_MAIN
              value: redis
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  selector:
    app: redis
